#!/bin/bash

# This script removes any text between the following 
#       <!-- ANS_START -->
#       <!-- ANS_END -->
# from an RMarkdown file to create a "student version" without answers.
# The answer is replaced with text that instructs the students to append
# their own solution, and a new Rmd file is generated with the suffix
# "-student" added to the original file.
anspath=$1
studpath="${anspath/.[Rr]md/_student.Rmd}"
if [ -f "$studpath" ] ; then
    rm "$studpath" ;
fi   
cp "$anspath" "$studpath"
ans_start_count=$(grep -o 'ANS_START' "$studpath" | wc -l)
ans_end_count=$(grep -o 'ANS_END' "$studpath" | wc -l)
if [ "$ans_start_count" -ne "$ans_end_count" ]; then
    echo "Check your script again. The number of occurences of ANS_START and ANS_END are not equal"
    exit 100 ;
fi
while grep 'ANS_START' "$studpath" > /dev/null;
do
    startLine=$(grep -n -m 1 'ANS_START' "$studpath" | sed 's/\([0-9]*\).*/\1/')
    stopLine=$(grep -n -m 1 'ANS_END' "$studpath" | sed 's/\([0-9]*\).*/\1/')
    del="$startLine","$stopLine"d
    sed -i.bak -e $del "$studpath"
    add="$startLine"i'*Write your code and solutions here.*' 
    sed -e "$add" -i.bak $studpath
done
rm "$studpath".bak
if [ -f temp.Rmd ] ; then
	rm temp.Rmd ;
fi
